### ISSUE TITLE
Each property of the CSS should be on a new line. 

### ISSUE THREAD

**Issue by josephtkim** [Adhi2903/prj-rev-bwfs-dasmoto#5]
For each line in CSS, it is best to place them on their own new line, and to indent the properties. Here is how your CSS should be formatted

```css
.mainheader {
  font-family: Helvetica; 
  font-size: 100px; 
  font-weight: bold; 
  color: khaki;
  text-align: center;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}

h2 {
  font-family: Helvetica; 
  font-size: 32px; 
  font-weight: bold; 
  color: white;
}

h3, p {
  font-family: Helvetica;
}

.brushes {
  background-color: mediumspringgreen;
}

.frames {
  background-color: lightcoral;
}

.paint {
  background-color: skyblue;
}

#price {
  font-family: Helvetica; 
  font-weight: bold; 
  color: blue;
}
```
