### ISSUE TITLE
Simplify CSS for all shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Adhi2903/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are several shared properties in your CSS code, which you can simplify like so

```css
.mainheader, h2, h3, p, #price {
  font-family: Helvetica;
  font-weight: bold;
}
```
